export interface TopicEntry {
  name: string;
  key: string;
  description: string;
  tags: string[];
}

export const GREEK_PHILOSOPHER_TOPICS: TopicEntry[] = [
  { name: "Socrates", key: "socrates", description: "Ancient Greek philosopher (470-399 BCE) from Athens. Known for the Socratic method of questioning and dialogue. Executed for corrupting youth; left no writings but influenced Plato profoundly.", tags: ["ancient-wisdom", "socrates", "ethics"] },
  { name: "Plato", key: "plato", description: "Student of Socrates (428-348 BCE). Founded the Academy and developed the Theory of Forms. Author of influential dialogues including The Republic and The Symposium.", tags: ["ancient-wisdom", "plato", "metaphysics"] },
  { name: "Aristotle", key: "aristotle", description: "Student of Plato (384-322 BCE). Founded his own school, the Lyceum. Pioneered logic, metaphysics, and empirical observation. Tutor to Alexander the Great.", tags: ["ancient-wisdom", "aristotle", "logic"] },
  { name: "Heraclitus", key: "heraclitus", description: "Pre-Socratic philosopher (540-480 BCE) from Ephesus. Known for the doctrine that all is in flux and the concept of the logos. Emphasized change and contradiction.", tags: ["ancient-wisdom", "heraclitus", "metaphysics"] },
  { name: "Epictetus", key: "epictetus", description: "Stoic philosopher (50-135 CE) from Phrygia. Emphasized personal freedom and virtue over external circumstances. Former slave who taught that only our judgments are in our control.", tags: ["ancient-wisdom", "epictetus", "stoicism"] },
  { name: "Marcus Aurelius", key: "marcus-aurelius", description: "Roman Stoic philosopher and Emperor (121-180 CE). Author of Meditations, personal reflections on Stoic philosophy. Ruled during times of plague and war while maintaining philosophical composure.", tags: ["ancient-wisdom", "marcus-aurelius", "stoicism"] },
  { name: "Seneca", key: "seneca", description: "Roman Stoic philosopher (4 BCE-65 CE) from Spain. Wrote essays on moral philosophy and letters to his student Lucilius. Political advisor to Nero; executed on suspicion of conspiracy.", tags: ["ancient-wisdom", "seneca", "stoicism"] },
  { name: "Diogenes", key: "diogenes", description: "Cynic philosopher (412-323 BCE) from Sinope. Known for radical rejection of social conventions and ascetic lifestyle. Famously asked Alexander the Great to step aside and stop blocking his sunlight.", tags: ["ancient-wisdom", "diogenes", "cynicism"] },
  { name: "Epicurus", key: "epicurus", description: "Greek philosopher (307-270 BCE) from Samos. Founded a school emphasizing simple living and friendship. Often misunderstood as advocating hedonism; actually promoted modest pleasure and absence of pain.", tags: ["ancient-wisdom", "epicurus", "ethics"] },
  { name: "Zeno of Citium", key: "zeno-citium", description: "Founder of Stoicism (335-263 BCE) from Cyprus. Taught in the Stoa Poikile, giving the school its name. Developed the idea that virtue is the only true good.", tags: ["ancient-wisdom", "zeno", "stoicism"] },
  { name: "Pythagoras", key: "pythagoras", description: "Mathematician and mystic philosopher (570-495 BCE) from Samos. Founded a religious and philosophical community. Associated mathematics with the structure of reality; famous for his geometric theorem.", tags: ["ancient-wisdom", "pythagoras", "mathematics"] },
  { name: "Democritus", key: "democritus", description: "Atomist philosopher (460-370 BCE) from Abdera. Proposed that all matter consists of atoms moving in void. Believed in determinism and the cheerful life (cheerfulness through understanding).", tags: ["ancient-wisdom", "democritus", "atomism"] },
  { name: "Thales", key: "thales", description: "Pre-Socratic philosopher (634-546 BCE) from Miletus. Considered the first Western philosopher. Proposed water as the fundamental substance; made contributions to geometry and astronomy.", tags: ["ancient-wisdom", "thales", "natural-philosophy"] },
  { name: "Parmenides", key: "parmenides", description: "Pre-Socratic philosopher (515-450 BCE) from Elea. Argued that reality is unchanging and eternal. His ideas profoundly challenged the notion of change and motion.", tags: ["ancient-wisdom", "parmenides", "metaphysics"] },
  { name: "Plotinus", key: "plotinus", description: "Neoplatonist philosopher (204-270 CE) from Egypt. Synthesized Platonism with mysticism. Developed the concept of The One as the ultimate principle of reality; influential on Christian, Islamic, and Jewish thought.", tags: ["ancient-wisdom", "plotinus", "neoplatonism"] },
];

export const GERMAN_PHILOSOPHER_TOPICS: TopicEntry[] = [
  { name: "Immanuel Kant", key: "kant", description: "Prussian philosopher (1724-1804). Revolutionary in epistemology with his Critique of Pure Reason. Developed the categorical imperative in ethics; shaped all subsequent Western philosophy.", tags: ["german-philosophy", "kant", "enlightenment"] },
  { name: "Georg Wilhelm Friedrich Hegel", key: "hegel", description: "German Idealist (1770-1831). Developed dialectical method and concept of historical progress through contradiction. Influenced Marx and shaped 19th-century philosophy profoundly.", tags: ["german-philosophy", "hegel", "idealism"] },
  { name: "Friedrich Nietzsche", key: "nietzsche", description: "Prussian philosopher (1844-1900). Challenged conventional morality and the death of God. Developed concepts of the Ubermensch and eternal recurrence; literary, aphoristic style.", tags: ["german-philosophy", "nietzsche", "existentialism"] },
  { name: "Arthur Schopenhauer", key: "schopenhauer", description: "German pessimist philosopher (1788-1860). Emphasized the blind will as reality's core. Influenced by Eastern philosophy; advocated asceticism and art as escape from suffering.", tags: ["german-philosophy", "schopenhauer", "pessimism"] },
  { name: "Martin Heidegger", key: "heidegger", description: "German existentialist (1889-1976). Developed fundamental ontology and analysis of Being. Major work Being and Time profoundly influenced 20th-century thought.", tags: ["german-philosophy", "heidegger", "existentialism"] },
  { name: "Karl Marx", key: "marx", description: "German philosopher and economist (1818-1883). Developed historical materialism and critique of capitalism. Co-authored The Communist Manifesto; foundational for modern political theory.", tags: ["german-philosophy", "marx", "materialism"] },
  { name: "Gottfried Wilhelm Leibniz", key: "leibniz", description: "German polymath (1646-1716). Developed monadology and pre-established harmony. Co-inventor of calculus; major contributor to logic, metaphysics, and natural philosophy.", tags: ["german-philosophy", "leibniz", "rationalism"] },
  { name: "Johann Gottlieb Fichte", key: "fichte", description: "German Idealist (1762-1814). Developed the transcendental idealism that influenced Hegel. Emphasized the self or ego as foundation of knowledge and reality.", tags: ["german-philosophy", "fichte", "idealism"] },
  { name: "Ludwig Wittgenstein", key: "wittgenstein", description: "Austrian-British philosopher (1889-1951). Revolutionized logic and language philosophy. Works include Tractatus Logico-Philosophicus and Philosophical Investigations.", tags: ["german-philosophy", "wittgenstein", "language"] },
  { name: "Edmund Husserl", key: "husserl", description: "Moravian philosopher (1859-1938), founded phenomenology. Developed the bracketing method to study consciousness. Influenced Heidegger and continental philosophy.", tags: ["german-philosophy", "husserl", "phenomenology"] },
  { name: "Hannah Arendt", key: "arendt", description: "German-Jewish political philosopher (1906-1975). Analyzed totalitarianism and the human condition. Works include The Human Condition and Eichmann in Jerusalem.", tags: ["german-philosophy", "arendt", "political"] },
  { name: "Theodor Adorno", key: "adorno", description: "German critical theorist (1903-1969). Co-founder of Frankfurt School. Critiqued culture industry and administered society; developed negative dialectics.", tags: ["german-philosophy", "adorno", "critical-theory"] },
  { name: "Walter Benjamin", key: "benjamin", description: "German theorist (1892-1940). Blended Marxism with Jewish mysticism. Wrote on modernity, art, language, and history; influential concept of the messianic.", tags: ["german-philosophy", "benjamin", "critical-theory"] },
  { name: "Karl Jaspers", key: "jaspers", description: "German existentialist (1883-1969). Emphasized human freedom, communication, and transcendence. Influenced postwar German thought and existentialist philosophy.", tags: ["german-philosophy", "jaspers", "existentialism"] },
];

export const FRENCH_PHILOSOPHER_TOPICS: TopicEntry[] = [
  { name: "Rene Descartes", key: "descartes", description: "French rationalist (1596-1650). Foundational for modern philosophy with Cogito, ergo sum. Developed method of doubt and mathematical philosophy of nature.", tags: ["french-philosophy", "descartes", "rationalism"] },
  { name: "Voltaire", key: "voltaire", description: "French Enlightenment writer and philosopher (1694-1778). Advocate for freedom of expression and religious tolerance. Satirist known for Candide; influenced the French Revolution.", tags: ["french-philosophy", "voltaire", "enlightenment"] },
  { name: "Jean-Jacques Rousseau", key: "rousseau", description: "Swiss-French philosopher (1712-1778). Developed concept of the social contract and general will. Emphasized nature and emotion; influenced Romanticism and democratic theory.", tags: ["french-philosophy", "rousseau", "enlightenment"] },
  { name: "Michel de Montaigne", key: "montaigne", description: "French Renaissance thinker (1533-1592). Pioneered the essay form with his Essais. Skeptical humanist; explored human nature and virtue through introspection and wide reading.", tags: ["french-philosophy", "montaigne", "humanism"] },
  { name: "Blaise Pascal", key: "pascal", description: "French mathematician and philosopher (1623-1662). Developed probability theory and contributed to calculus. Philosophy emphasizes the heart over reason; famous for Pascal's Wager.", tags: ["french-philosophy", "pascal", "faith"] },
  { name: "Jean-Paul Sartre", key: "sartre", description: "French existentialist (1905-1980). Central figure of existentialism with emphasis on freedom and responsibility. Works include Being and Nothingness; politically engaged throughout life.", tags: ["french-philosophy", "sartre", "existentialism"] },
  { name: "Albert Camus", key: "camus", description: "French-Algerian philosopher (1913-1960). Explored absurdism and the meaninglessness of existence. Major works include The Stranger and The Myth of Sisyphus.", tags: ["french-philosophy", "camus", "absurdism"] },
  { name: "Simone de Beauvoir", key: "de-beauvoir", description: "French existentialist (1908-1986). Pioneering feminist philosopher and writer. Wrote The Second Sex analyzing women's oppression; explored freedom, ethics, and gender.", tags: ["french-philosophy", "de-beauvoir", "feminism"] },
  { name: "Michel Foucault", key: "foucault", description: "French poststructuralist (1926-1984). Analyzed power, knowledge, sexuality, and discourse. Influenced postmodern and critical theory; works examine institutions and normalization.", tags: ["french-philosophy", "foucault", "poststructuralism"] },
  { name: "Jacques Derrida", key: "derrida", description: "Algerian-French poststructuralist (1930-2004). Developed deconstruction as method of textual analysis. Challenged Western metaphysics; controversial and influential figure.", tags: ["french-philosophy", "derrida", "poststructuralism"] },
  { name: "Maurice Merleau-Ponty", key: "merleau-ponty", description: "French phenomenologist (1908-1961). Developed philosophy of embodiment and perception. Emphasized the role of the body in consciousness and knowledge.", tags: ["french-philosophy", "merleau-ponty", "phenomenology"] },
  { name: "Henri Bergson", key: "bergson", description: "French philosopher (1859-1941). Developed concepts of elan vital and creative evolution. Influenced metaphysics and process philosophy; emphasized intuition over intellect.", tags: ["french-philosophy", "bergson", "metaphysics"] },
  { name: "Denis Diderot", key: "diderot", description: "French Enlightenment philosopher (1713-1784). Editor of the Encyclopedia; explored materialism and atheism. Advocate for reason, science, and human freedom.", tags: ["french-philosophy", "diderot", "enlightenment"] },
  { name: "La Rochefoucauld", key: "la-rochefoucauld", description: "French nobleman and moralist (1613-1680). Author of Maximes exploring human nature and self-interest. Wrote aphorisms revealing hidden motives beneath virtuous appearances.", tags: ["french-philosophy", "la-rochefoucauld", "ethics"] },
  { name: "Montesquieu", key: "montesquieu", description: "French Enlightenment thinker (1689-1755). Developed separation of powers theory; analyzed climate's influence on society. The Spirit of the Laws profoundly influenced political thought.", tags: ["french-philosophy", "montesquieu", "enlightenment"] },
];

export const FICTION_AUTHOR_TOPICS: TopicEntry[] = [
  { name: "William Shakespeare", key: "shakespeare", description: "English dramatist and poet (1564-1616). Greatest writer in English language. Created 37 plays and 154 sonnets exploring human nature, ambition, love, and tragedy.", tags: ["literary-wisdom", "shakespeare", "english"] },
  { name: "Charles Dickens", key: "dickens", description: "English novelist (1812-1870). Master of social realism and character creation. Works like Great Expectations and David Copperfield exposed Victorian social injustice.", tags: ["literary-wisdom", "dickens", "english"] },
  { name: "Jane Austen", key: "austen", description: "English novelist (1775-1817). Pioneer of psychological realism in fiction. Witty observations of love, marriage, and social class in regency England.", tags: ["literary-wisdom", "austen", "english"] },
  { name: "Oscar Wilde", key: "wilde", description: "Irish writer (1854-1900). Master of wit, paradox, and aesthetic philosophy. Works include The Picture of Dorian Gray and The Importance of Being Earnest.", tags: ["literary-wisdom", "wilde", "english"] },
  { name: "George Orwell", key: "orwell", description: "English novelist and essayist (1903-1950). Explored totalitarianism and language's power. Wrote 1984 and Animal Farm; advocated plain speaking against doublethink.", tags: ["literary-wisdom", "orwell", "english"] },
  { name: "J.R.R. Tolkien", key: "tolkien", description: "English author (1892-1973). Created Middle-earth and revolutionary fantasy genre. The Lord of the Rings and The Hobbit remain touchstones of modern literature.", tags: ["literary-wisdom", "tolkien", "english"] },
  { name: "Victor Hugo", key: "hugo", description: "French novelist (1802-1885). Master of epic narrative and social commentary. Les Miserables and Notre-Dame de Paris explore justice, redemption, and human dignity.", tags: ["literary-wisdom", "hugo", "french"] },
  { name: "Gustave Flaubert", key: "flaubert", description: "French novelist (1821-1880). Pioneer of literary realism. Madame Bovary revolutionized the novel through meticulous prose and psychological depth.", tags: ["literary-wisdom", "flaubert", "french"] },
  { name: "Marcel Proust", key: "proust", description: "French novelist (1871-1922). Wrote In Search of Lost Time, exploring memory and consciousness. Pioneered stream of consciousness and psychological realism in epic form.", tags: ["literary-wisdom", "proust", "french"] },
  { name: "Alexandre Dumas", key: "dumas", description: "French novelist (1802-1870). Master of adventure and historical fiction. The Count of Monte Cristo and The Three Musketeers remain beloved classics.", tags: ["literary-wisdom", "dumas", "french"] },
  { name: "Johann Wolfgang von Goethe", key: "goethe", description: "German writer (1749-1832). Towering figure of German literature and Romanticism. Faust and The Sorrows of Young Werther explore human aspiration and emotion.", tags: ["literary-wisdom", "goethe", "german"] },
  { name: "Franz Kafka", key: "kafka", description: "Czech-German writer (1883-1924). Master of absurdism and alienation. The Trial and The Metamorphosis explore bureaucracy, isolation, and existential anxiety.", tags: ["literary-wisdom", "kafka", "german"] },
  { name: "Thomas Mann", key: "mann", description: "German novelist (1875-1955). Explored German culture and the human condition. The Magic Mountain and Buddenbrooks remain major achievements of European literature.", tags: ["literary-wisdom", "mann", "german"] },
  { name: "Hermann Hesse", key: "hesse", description: "German-Swiss writer (1877-1962). Explored spiritual search and individuality. Steppenwolf and Siddhartha resonate with seekers of meaning and self-discovery.", tags: ["literary-wisdom", "hesse", "german"] },
  { name: "Fyodor Dostoevsky", key: "dostoevsky", description: "Russian novelist (1821-1881). Master of psychological depth and moral philosophy. Crime and Punishment and The Brothers Karamazov remain pinnacles of world literature.", tags: ["literary-wisdom", "dostoevsky", "russian"] },
  { name: "Leo Tolstoy", key: "tolstoy", description: "Russian novelist (1828-1910). Epic chronicler of human experience. War and Peace and Anna Karenina are masterpieces of realism exploring fate, love, and society.", tags: ["literary-wisdom", "tolstoy", "russian"] },
];

export const CLASSICAL_AUTHOR_TOPICS: TopicEntry[] = [
  { name: "Homer", key: "homer", description: "Ancient Greek epic poet (8th century BCE). Author of the Iliad and the Odyssey. Foundational works of Western literature depicting war, heroism, and human suffering.", tags: ["classical-literature", "homer", "greek"] },
  { name: "Sophocles", key: "sophocles", description: "Ancient Greek dramatist (496-406 BCE). Master of tragic drama. Oedipus Rex and Antigone explore fate, hubris, and human responsibility.", tags: ["classical-literature", "sophocles", "greek"] },
  { name: "Euripides", key: "euripides", description: "Ancient Greek dramatist (480-406 BCE). Questioned traditional myths and values. The Bacchae and Medea explore madness, passion, and the destructive power of the divine.", tags: ["classical-literature", "euripides", "greek"] },
  { name: "Aeschylus", key: "aeschylus", description: "Ancient Greek dramatist (525-456 BCE). Pioneer of tragedy. The Oresteia trilogy and Prometheus Bound explore justice, fate, and divine punishment.", tags: ["classical-literature", "aeschylus", "greek"] },
  { name: "Aristophanes", key: "aristophanes", description: "Ancient Greek comic dramatist (446-386 BCE). Master of satire and political comedy. Lysistrata and The Frogs mock authority while celebrating language and wit.", tags: ["classical-literature", "aristophanes", "greek"] },
  { name: "Virgil", key: "virgil", description: "Roman poet (70-19 BCE). Author of the Aeneid, an epic tracing Rome's legendary origin. The Georgics explore rural life; profoundly influenced Western literature.", tags: ["classical-literature", "virgil", "roman"] },
  { name: "Ovid", key: "ovid", description: "Roman poet (43 BCE-17 CE). Master of metamorphosis and narrative. Metamorphoses retells myths with wit and psychological insight; hugely influential on European culture.", tags: ["classical-literature", "ovid", "roman"] },
  { name: "Horace", key: "horace", description: "Roman poet (65-8 BCE). Master of satire, odes, and epistles. Carpe diem philosophy and polished verse made him beloved across centuries.", tags: ["classical-literature", "horace", "roman"] },
  { name: "Cicero", key: "cicero", description: "Roman orator and philosopher (106-43 BCE). Greatest Latin prose stylist. Speeches and philosophical works shaped rhetoric and thought; executed in civil war.", tags: ["classical-literature", "cicero", "roman"] },
  { name: "Plutarch", key: "plutarch", description: "Greek-Roman biographer and essayist (46-119 CE). Author of Parallel Lives comparing Greek and Roman figures. Essays explore ethics and human nature with wit and wisdom.", tags: ["classical-literature", "plutarch", "greco-roman"] },
  { name: "Lucretius", key: "lucretius", description: "Roman poet (94-55 BCE). Expounded Epicurean atomism in verse. De rerum natura (On the Nature of Things) explores materialism and freedom from fear.", tags: ["classical-literature", "lucretius", "roman"] },
  { name: "Sappho", key: "sappho", description: "Ancient Greek lyric poet (630-570 BCE) from Lesbos. Master of love poetry and emotion. Nine books of poems survive in fragments; revolutionized lyric poetry.", tags: ["classical-literature", "sappho", "greek"] },
  { name: "Pindar", key: "pindar", description: "Ancient Greek lyric poet (518-438 BCE). Celebrated Olympic victors in elaborate odes. Master of myth, metaphor, and choral poetry; influenced Greek and Roman literature.", tags: ["classical-literature", "pindar", "greek"] },
  { name: "Juvenal", key: "juvenal", description: "Roman satirist (55-140 CE). Master of savage social satire. Sixteen satires attack vice, corruption, and absurdity of Roman society with bitter wit.", tags: ["classical-literature", "juvenal", "roman"] },
  { name: "Martial", key: "martial", description: "Roman epigrammatist (40-103 CE) from Spain. Master of witty, biting epigrams. Fifteen books of short, clever verses on Roman life and society.", tags: ["classical-literature", "martial", "roman"] },
];

/** Get all topics for a given fallback content type */
export function getTopicsForType(contentType: string): TopicEntry[] {
  switch (contentType) {
    case "greek_philosopher": return GREEK_PHILOSOPHER_TOPICS;
    case "german_philosopher": return GERMAN_PHILOSOPHER_TOPICS;
    case "french_philosopher": return FRENCH_PHILOSOPHER_TOPICS;
    case "fiction_author": return FICTION_AUTHOR_TOPICS;
    case "classical_author": return CLASSICAL_AUTHOR_TOPICS;
    default: return [];
  }
}
